image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install
    command: docker run --name postgres-database -e POSTGRES_PASSWORD=docker -p 5432:5432 -d postgres && docker start postgres-database && yarn dev

    
