
ports:
  - port: 3333
    onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn install # runs during prebuild
    command: yarn dev